apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-webapp
  name: hello-webapp
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-webapp
  template:
    metadata:
      labels:
        app: hello-webapp
    spec:
      containers:
      - image: asendzhingarov/hello-webapp:latest
        name: hello-webapp
        stdin: true
