apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-webapp-svc
  name: hello-webapp-svc
  namespace: mynamespace
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: hello-webapp
  type: NodePort
